### ISSUE TITLE
Composer require vs require-dev

### ISSUE THREAD

**Issue by thefrosty** [inpsyde/php-coding-standards#19]
Curious as to why you've got most of these packages in the require vs the require-dev:
```
"require": {
    "php": ">=7.0",
    "squizlabs/php_codesniffer": "^3",
    "dealerdirect/phpcodesniffer-composer-installer": "^0.4",
    "wp-coding-standards/wpcs": "^0.14",
    "automattic/phpcs-neutron-standard": "^1",
    "wimg/php-compatibility": "^8.0"
  },
  "require-dev": {
    "phpunit/phpunit": "6.0.*"
},
```

I personally don't want all those packages going up to my PROD box.

**Comment by widoz** [comment]
If you define the inpsyde/php-coding-standard as dev package you'll not have it's requires into you prod. Afaik the requires are for the inpsyde package  because it need the to work properly in your dev env. As you can read here https://getcomposer.org/doc/04-schema.md#require the packages env doesn't scale up on your env.

**Comment by bueltge** [comment]
I close this issue because the answer from @widoz is solid. For our codex is it necessary to use require, but in other projects you should use it via reuire-dev, only for development. 
Thanks for your interest on our standard @thefrosty Great to see, that the open repository for this topic is a good idea.
