### ISSUE TITLE
Remove WordPressVIPMinimum.VersionControl.MergeConflict in favor of the new sniff

### ISSUE THREAD

**Issue by meszarosrob** [inpsyde/php-coding-standards#40]
The VIP Coding Standards removed `WordPressVIPMinimum.VersionControl.MergeConflict` sniff in favor of `Generic.VersionControl.GitMergeConflict`. See the changelog here: https://github.com/Automattic/VIP-Coding-Standards/releases/tag/2.1.0.

We still reference it https://github.com/inpsyde/php-coding-standards/blob/529e046bd9b921bca40cb95ebfd65d743cdf0215/Inpsyde/ruleset.xml#L129 and it causes an error when running `phpcs`.

```
ERROR: Referenced sniff "WordPressVIPMinimum.VersionControl.MergeConflict" does not exist
```

We don't require a specific version of the VIP CS:

https://github.com/inpsyde/php-coding-standards/blob/8b3abeb0ec546c025e4c3b546981bc37e8feaebf/composer.json#L34

**Comment by gmazzap** [comment]
> We don't require a specific version of the VIP CS

Yes, we require latest version of v2 series, because if we require a specific version then we need to update the version everytime they fix a bug and so on.

Requiring the _latest in v2 series_ in theory should preserve us from things like that: removing a rule is surely a breaking change and should not be done without increasing the major version... but looks like VIP doesn't really care about it.

My opinion is to keep the requirement as-is and replace `WordPressVIPMinimum.VersionControl.MergeConflict` with `Generic.VersionControl.GitMergeConflict`.
